# Generated by Django 2.2.12 on 2022-10-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citacao', models.CharField(max_length=5000)),
                ('autor', models.CharField(max_length=200)),
            ],
        ),
    ]
