# Generated by Django 2.2.12 on 2022-10-30 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citacoesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacoes',
            name='data_da_publicacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
